version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - nifi-kafka-network

  nifi-registry:
    image: apache/nifi-registry:0.5.0
    ports:
      - 18080:18080
    networks:
      - nifi-kafka-network

  nifi:
    image: apache/nifi:1.18.0
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    networks:
      - nifi-kafka-network

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - nifi-kafka-network

  kafka-console-consumer:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-console-consumer
    command: ["kafka-console-consumer", "--bootstrap-server", "broker:29092", "--topic", "your_topic_name"]
    depends_on:
      - broker
    networks:
      - nifi-kafka-network

networks:
  nifi-kafka-network:
    external: true

